use_frameworks!

platform :ios, '12.0'

target 'EgoiPushLibrary_Example' do
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'EgoiPushLibrary', '~> 1.0.18'
#  pod 'EgoiPushLibrary', :path => '../'
end
