use_frameworks!

platform :ios, '12.0'

def common_pods
  pod 'Firebase/Messaging'
end

target 'EgoiPushLibrary_Example' do
  common_pods
#  pod 'EgoiPushLibrary', :path => '../'
  pod 'EgoiPushLibrary', '2.0.2'
end

target 'NotificationService' do
  common_pods
end
