use_frameworks!

platform :ios, '12.0'

def common_pods
  pod 'Firebase/Messaging'
  #  pod 'EgoiPushLibrary'
end

target 'EgoiPushLibrary_Example' do
  common_pods
  pod 'EgoiPushLibrary', :path => '../'
end

target 'NotificationService' do
  common_pods
end
